const APP_NAME = 'ListIt';
const API_HEALTHCHECK_MESSAGE = `${APP_NAME} API is running`;
const DEFAULT_CATEGORY_NAME = 'Other';
const DEFAULT_ITEM_SUBCATEGORY = 'Misc';
const DEFAULT_SHOW_PUBLIC = true;
const DEFAULT_SHOW_PINNED_ONLY = false;
const DEFAULT_ITEM_SORT_MODE = 'subcategory';
const ITEM_SORT_MODES = ['name', 'subcategory'];
const COLLABORATOR_PERMISSIONS = {
  READ: 'READ',
  ADD_REMOVE: 'ADD_REMOVE',
  EDIT_ALL: 'EDIT_ALL'
};
const DEFAULT_PUBLIC_CATEGORIES = [
  'To Do',
  'Movies',
  'Novels',
  'Animes',
  'Series',
  'Hotels',
  'Trips',
  'Treks',
  'Eateries'
];

module.exports = {
  APP_NAME,
  API_HEALTHCHECK_MESSAGE,
  DEFAULT_CATEGORY_NAME,
  DEFAULT_ITEM_SUBCATEGORY,
  DEFAULT_SHOW_PUBLIC,
  DEFAULT_SHOW_PINNED_ONLY,
  DEFAULT_ITEM_SORT_MODE,
  ITEM_SORT_MODES,
  COLLABORATOR_PERMISSIONS,
  DEFAULT_PUBLIC_CATEGORIES
};
