const PORT = process.env.PORT || 4000;
const CORS_ORIGIN = process.env.CORS_ORIGIN;
const MONGO_URI = process.env.MONGO_URI;
const ADMIN_UID = process.env.ADMIN_UID;
const FIREBASE_SERVICE_ACCOUNT_KEY = process.env.FIREBASE_SERVICE_ACCOUNT_KEY
  ? JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_KEY)
  : null;
const CRYPTO_SERVICE_URL = process.env.CRYPTO_SERVICE_URL || null;
const CRYPTO_SERVICE_TOKEN = process.env.CRYPTO_SERVICE_TOKEN || null;
const CRYPTO_SERVICE_TIMEOUT_MS = Number(process.env.CRYPTO_SERVICE_TIMEOUT_MS || 5000);
const PRIVATE_LIST_ENCRYPTION_REQUIRED = process.env.PRIVATE_LIST_ENCRYPTION_REQUIRED === 'true';
const ALLOW_INSECURE_INTERNAL_CRYPTO_SERVICE =
  process.env.ALLOW_INSECURE_INTERNAL_CRYPTO_SERVICE === 'true';

module.exports = {
  PORT,
  CORS_ORIGIN,
  MONGO_URI,
  ADMIN_UID,
  FIREBASE_SERVICE_ACCOUNT_KEY,
  CRYPTO_SERVICE_URL,
  CRYPTO_SERVICE_TOKEN,
  CRYPTO_SERVICE_TIMEOUT_MS,
  PRIVATE_LIST_ENCRYPTION_REQUIRED,
  ALLOW_INSECURE_INTERNAL_CRYPTO_SERVICE
};
